### PR TITLE
Removed nonsense

### PR DESCRIPTION
**Pull request by cschroedl-gov**
Addresses #183

### CODE REVIEW

**Comment by vsoch** [comment]
haha, it looks like someone --> https://github.com/singularityware/singularityware.github.io/blame/3fc939524f7d29eb8ed24ea90c42db17fe2de66f/pages/info/about.md#L70 (@gmkurtzer !) got a little excited about Asciinemas, as anyone would! We should verify that he doesn't have a plan to add them there, and if not, yes definitely just remove the line. I also know @GodloveD was big into Asciinemas so he can comment as well!

**Review by GodloveD — APPROVED** [review]
Yeah.  I am still big into asciinemas.  Just no time.  lol

Fine by me to remove.

:shipit:

**Comment by vsoch** [comment]
Thanks @GodloveD !

**Comment by cschroedl-gov** [comment]
I didn't know about Asciinemas. Thanks for the hot tip! Most helpful typo ever?

**Comment by vsoch** [comment]
Definitely!! Ascinemas are amazing... I must have close to 100 now!

**Comment by cschroedl-gov** [comment]
:100:

**Pull request merged**
