### PR TITLE
installation instructions for windows

### PR DESCRIPTION
**Pull request by alaindomissy**

### CODE REVIEW

**Comment by vsoch** [comment]
This is a huge improvement! My one comment is that we possibly would want to discourage using older versions of Singularity (that may have less functionality or security issues) - if the user is looking for an older version he/she could go to the link on hashicorp. What are your thoughts?

**Comment by vsoch** [comment]
thanks!

**Comment by alaindomissy** [comment]
I agree. I would even suggest only have a link to the latest version on this site.  And may be a link to this: https://app.vagrantup.com/singularityware for older versions. I can n=make a new PR with this change if you wish. Thanks!

**Comment by vsoch** [comment]
Let's make the change whenever either of us works on it next, it should be a few simple lines. If you have free time go for it, but there is definitely no need to rush.

**Comment by alaindomissy** [comment]
OK. I noticed a typo on the mac instructions. I had left 2.3 instead of 2.3.i in the bash code.
So I just made a PR to fix that, plus the old versions idea. Please check how it looks. And I ll update the windows page at some point too. Thanks.

**Pull request merged**
