### PR TITLE
add: Mac + Windows installation via Docker

### PR DESCRIPTION
**Pull request by kaczmarj**
This PR adds: 

- an alternative to Singularity via Vagrant for macOS users
- a Dockerfile that builds a minimal Docker image containing Singularity
- instructions to install and use the Docker image on Mac and Windows (not tested on Windows)

As a test, I set up an automated build on [DockerHub](https://hub.docker.com/r/kaczmarj/singularity/) that builds a Docker image from the Dockerfile in my fork of this repository. This image is available for download via the command `docker pull kaczmarj/singularity`. If this PR is accepted, a dedicated DockerHub repository could be created to host the Singularity Docker image.

Thank you.

### CODE REVIEW

**Comment by vsoch** [comment]
hey @kaczmarj, did you see https://github.com/singularityware/docker2singularity? Would it be more appropriate to PR to that repo?

**Comment by kaczmarj** [comment]
@vsoch - thanks for pointing me to `docker2singularity`, but I don't think this PR would be relevant there. My intention is to supplement the instructions on http://singularity.lbl.gov/install-mac. That webpage explains how to install Singularity with Vagrant, so I wanted to provide the same functionality but through Docker. I guess a related question is, would you recommend using `docker2singularity` instead of the instructions on http://singularity.lbl.gov/install-mac?

**Comment by vsoch** [comment]
ah thanks for the clarification @kaczmarj ! Since 2.3 is to support import from docker without sudo, docker2singularity is not planned to be part of the docs proper, but just referenced with a link to the docker2singularity repo. So my suggestion is the following:

- update the docs / image at docker2singularity, they will primarily live there
- check the docs/2.3 branch on this repo and make sure the link is correctly placed and this is specified.

Let me know if that makes sense!

**Comment by kaczmarj** [comment]
Thanks @vsoch, makes sense to me. Closing.

**Pull request closed without merging**
