### PR TITLE
Adding some more documentation for --nv and $SINGULARITY_ENVIRONMENT

### PR DESCRIPTION
**Pull request by GodloveD**
@vsoch I started with master here, made some changes, created a branch and then merged 2.4 into it.  Looks like it picked up some commits that you made to master.  These appear to be things that should also be added to the 2.4 branch as well, but you should make the final call.  I've checked the box that Allows edits from maintainers so if something needs tweaking feel free to have at it.

### CODE REVIEW

**Comment by vsoch** [comment]
Thanks @GodloveD ! I just merged this by pushing from another branch (also with the updates from old master, and new updates to master) and we are good to go! Thanks again for these awesome fixes, you are the  :100: documentation masta' winner!

**Comment by GodloveD** [comment]
Woo Hoo.  Thanks for catching those typos Ms Host System. 😜

**Comment by GodloveD** [comment]
Wait.  This didn't work properly.  I added documentation for the `$SINGULARITY_ENVIRONMENT` variable in this request and it got lost.  Can you have a look?

**Comment by GodloveD** [comment]
For instance, I'm not seeing this line or those below it in the merged version. https://github.com/singularityware/singularityware.github.io/pull/101/files#diff-cea51d4d0c721b07ad02aea1a5319049R154
Am I missing something?

**Comment by vsoch** [comment]
yeah I don't understand why that happened! I merged your branch with this change and it went away. Can you open this again so we can compare again? Sorry about that :(

**Comment by GodloveD** [comment]
I'm pretty sure it was because I did something silly in Git.  With all the time I've invested in Git I will be really surprised if it ever actually saves me any time.  

Unfortunately, I got a little trigger happy after I saw that the PR was closed, so I can't re-open the PR.  😱 
screen shot 2017-08-22 at 12 33 27 pm

**Pull request closed without merging**
