### PR TITLE
changing ordering of sidebar

### PR DESCRIPTION
**Pull request by vsoch**
how is this @GodloveD ?

### CODE REVIEW

**Comment by vsoch** [comment]
This will close #123

**Comment by GodloveD** [comment]
This is weird.  When I go to the "Build an Image" page, the ordering is correct, but there is another bug:  Both the "Build an Image" page and the `build` command page are highlighted in the sidebar:
screen shot 2017-10-05 at 12 47 55 pm
When I navigate to another page, the ordering is incorrect again:
screen shot 2017-10-05 at 12 48 19 pm

**Comment by vsoch** [comment]
No that is correct, it's the same page and it is used twice, so it highlights twice.

**Comment by GodloveD** [comment]
OK.  That explains why both sections are highlighted, but it doesn't explain why the sidebar elements re-arrange themselves depending on which page I'm on.

Something seems seriously wrong to me.  If I go to the Running Services page, the Singularity Flow section disappears from the sidebar altogether.  
screen shot 2017-10-05 at 1 54 02 pm


What is happening?? 😱

**Comment by vsoch** [comment]
I can't reproduce this. 
image

Could you please look in the console for errors, ensure no blocking is on, open the console and make sure that the cache is cleared when it's open, check the jekyll output to make sure you aren't missing an error to prevent updates to rendering, and then stop the server, `rm -rf _site` and then again `bundle exec jekyll build`?

**Comment by GodloveD** [comment]
Ahh!  I had looked at/done everything you suggested except `rm -rf _site`.  That did the trick.  This looks good.  And I will merge the associated PR.

**Pull request merged**
