### PR TITLE
clarified user binding (hopefully)

### PR DESCRIPTION
**Pull request by GodloveD**
Hopefully these comments will save some admin a little time.

### CODE REVIEW

**Comment by vsoch** [comment]
ready for review?

**Comment by GodloveD** [comment]
I think I actually pushed it a bit early. Can I get back with you tomorrow
AM?

**Comment by vsoch** [comment]
you bet! That's why I checked :) That's actually really good, because I looked into why travis wasn't building, and for some reason it was just triggering from your circle account! It must have disabled the main one or something strange... anyway I re-enabled it, so your update tomorrow morning will be a good test if the travis is working again to preview changes.

**Comment by GodloveD** [comment]
Weird. Hope it works now.

**Comment by vsoch** [comment]
actually it was building on circle - the travis was disabled because there isn't an easy/free artifacts option. I'm going to look into why it's not building on circle, and hopefully you have one more push haha.

**Comment by GodloveD** [comment]
I don't currently have a circle account.  Do I need to get one?  Anyway,
I'd better walk the dog and go to bed.  I can push again in the morning if
you need another test. :-)

**Comment by vsoch** [comment]
No you shouldn't need to! It should build all PRs, even if you don't have an account (because it's hooked up via my account). I just reset the build, and enabled PRs, so it may be the case that this one doesn't work, in which case we can try again next time. It's not a huge deal, because I can pull and preview locally, but it will be nice to have.

**Comment by GodloveD** [comment]
I think this should be ready for review now.  I'm happy to make dummy
pushes on this or another PR too if you need more testing for CircleCI.

**Comment by vsoch** [comment]
Just previewed locally - looks good! I think this will be very helpful. Thanks again for making this more clear for the admin/user!

**Pull request merged**
